<a href="https://colab.research.google.com/github/nmonson1/recreational_programming/blob/main/foobar_eigenvec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
matr = [[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]]
#desired output [7,6,8,21]
#matr = [[0, 1, 0, 0, 0, 1], [4, 0, 0, 3, 2, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
#desired output [0, 3, 2, 9, 14]
solution(matr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


LinAlgError: ignored

In [ ]:
#I had a solution with sympy that I made myself, but sympy isn't supported. I looked up some help on absorbing markov chains to get the following:
import numpy as np

class frac():
    def __init__(self,p,q):
        self.p=p
        self.q=q


"""def simplify(array):
    result = array
    #we store an array of fractions as their numerators, then 2 extra entries: the common denominator for the row and a label for which row was originally here.
    denom_list = []
    for row in result:
        gcd = np.gcd.reduce(row)
        for i,entry in enumerate(row[0:-1]):
            row(i)=int(entry/gcd)
        denom_list.append(row[-2])
    return result"""

def row_reduce(m,d):
    num_rows, num_cols = m.shape
    h=0
    k=0
    lcm=np.lcm.reduce(d)


    while (h < num_rows and k < num_cols):
        i_max = h
        for x in range(num_rows-h):
            if np.abs(m[i_max+x][k]) > np.abs(m[i_max][k]):
                i_max = i_max+x

        if m[i_max, k] == 0:
            k = k + 1
        else:
            #print(m[h],m[i_max])
            m[[h,i_max]]=m[[i_max,h]]
            #d[[h,i_max]]=d[[i_max,h]]
            #print(m[h],m[i_max])
            for i in np.hstack((np.arange(h),np.arange(h+1,num_rows))):
                #print(lcm,m[h,k])
                newlcm=np.lcm(lcm,m[h,k])
                factor=int(newlcm/lcm)
                m=factor*m
                lcm=newlcm

                f = float(m[i, k]) / float(m[h, k])
                #print(m[i, k] , m[h, k])
                #/* Fill with zeros the lower part of pivot column: */
                m[i, k] = 0
                #/* Do for all remaining elements in current row: */
                for j in range(k+1,num_cols):
                    #print(i,j,f)
                    m[i, j] = m[i, j] - int(m[h, j] * f)
            #/* Increase pivot row and column */
            h = h + 1
            k = k + 1
    return m,lcm


def solution(m):
    dim = len(m)
    sl=[]
    transients=[]
    tl=[]
    d=[]
    for i,row in enumerate(m):
        if sum(row)==0:
            sl.append(i) #add labels to rows
        else:
            transients.append(np.asarray(row)) #add denominators to rows
            d.append(sum(row))
            tl.append(i) #add labels to rows

    T=np.asarray(transients)
    R=T[:,sl]
    S=T[:,tl]
    D=np.asarray(d)
    lcm=np.lcm.reduce(d)
    print(S)
    print(R)
    for i,denom in enumerate(d):
        S[i]=S[i]*lcm/denom
        R[i]=R[i]*lcm/denom
    M=np.hstack(((lcm*np.eye(len(S),dtype=int)-S),R))
    print(S)
    print(R)
    m,lcm=row_reduce(M,D)

    print(m,lcm)
    first=m[0][-len(sl):]

    print(first,sum(first))
#    transarray = np.ndarray(m)
#    transarray = simplify(transarray)

    #put matrix into form (absorb | 0 )
    #                     (R      | S )
    #
    #We want a row of     (absorb      | 0 )
    #                     ((Id-S)^-1 R | 0 )

    #((Id-S) | R)





In [ ]:
#matr = [[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]]
#desired output [7,6,8,21]
matr = [[0, 1, 0, 0, 0, 1], [4, 0, 0, 3, 2, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
#desired output [0, 3, 2, 9, 14]
#solution(matr)

In [ ]:
#m=np.reshape(np.arange(30),(5,6))
m=np.asarray([[2,7,1,0],[1,4,0,1],[2,4,1,5]])
n=row_reduce(m,d=np.ones(len(m),dtype=int))
n[0][0]/72,n[0][1]/-108,n[0][2]/-18

(array([1.        , 0.        , 0.        , 7.66666667]),
 array([-0.        ,  1.        , -0.        , -1.66666667]),
 array([-0.        , -0.        ,  1.        , -3.66666667]))

Making fuel for the LAMBCHOP's reactor core is a tricky process because of the exotic matter involved. It starts as raw ore, then during processing, begins randomly changing between forms, eventually reaching a stable form. There may be multiple stable forms that a sample could ultimately reach, not all of which are useful as fuel.

Commander Lambda has tasked you to help the scientists increase fuel creation efficiency by predicting the end state of a given ore sample. You have carefully studied the different structures that the ore can take and which transitions it undergoes. It appears that, while random, the probability of each structure transforming is fixed. That is, each time the ore is in 1 state, it has the same probabilities of entering the next state (which might be the same state).  You have recorded the observed transitions in a matrix. The others in the lab have hypothesized more exotic forms that the ore can become, but you haven't seen all of them.

Write a function solution(m) that takes an array of array of nonnegative ints representing how many times that state has gone to the next state and return an array of ints for each terminal state giving the exact probabilities of each terminal state, represented as the numerator for each state, then the denominator for all of them at the end and in simplest form. The matrix is at most 10 by 10. It is guaranteed that no matter which state the ore is in, there is a path from that state to a terminal state. That is, the processing will always eventually end in a stable state. The ore starts in state 0. The denominator will fit within a signed 32-bit integer during the calculation, as long as the fraction is simplified regularly.

For example, consider the matrix m:
[
  [0,1,0,0,0,1],  # s0, the initial state, goes to s1 and s5 with equal probability
  [4,0,0,3,2,0],  # s1 can become s0, s3, or s4, but with different probabilities
  [0,0,0,0,0,0],  # s2 is terminal, and unreachable (never observed in practice)
  [0,0,0,0,0,0],  # s3 is terminal
  [0,0,0,0,0,0],  # s4 is terminal
  [0,0,0,0,0,0],  # s5 is terminal
]
So, we can consider different paths to terminal states, such as:
s0 -> s1 -> s3
s0 -> s1 -> s0 -> s1 -> s0 -> s1 -> s4
s0 -> s1 -> s0 -> s5
Tracing the probabilities of each, we find that
s2 has probability 0
s3 has probability 3/14
s4 has probability 1/7
s5 has probability 9/14
So, putting that together, and making a common denominator, gives an answer in the form of
[s2.numerator, s3.numerator, s4.numerator, s5.numerator, denominator] which is
[0, 3, 2, 9, 14].